### PR TITLE
FO: add error message modal display

### PR DESCRIPTION
**Pull request by reho**
I've made some modifications to handle cart adding errors.

### CODE REVIEW

**Comment by axometeam** [comment]
Good idea ! thanks

**Comment by francoispeyret** [comment]
Good idea, thanks !

**Comment by marionf** [comment]
@reho 

I just tested your PR

The modal isn't displayed anymore if the product is out of stock and the product page is not refreshed.
So, it's like add to cart button didn't do anything, but the product is anyway added to the cart and the product page is like blocked

Video: https://drive.google.com/file/d/1F67XapHrknmIH4oAqC1Vk1ljQsQEi5SJ/view?usp=sharing

**Comment by matks** [comment]
Interesting idea 🤔
This PR might need some updating as it was done a long time ago, but the idea has potential 👍

**Comment by matks** [comment]
Issue was fixed by PR PrestaShop/ps_shoppingcart#41 so this PR is not relevant anymore

Thank your for the contribution anyway, sorry for the late answer

**Pull request closed without merging**
