### PR TITLE
Release 2.0.3

### PR DESCRIPTION
**Pull request by matks**
Summary of main bug fixes for this patch version:
- multiple codestyle fixes (see https://github.com/PrestaShop/ps_shoppingcart/pull/29 for example)
- behavior bugfix https://github.com/PrestaShop/ps_shoppingcart/pull/20
- behavior bugfix https://github.com/PrestaShop/ps_shoppingcart/pull/41
- tech bugfix https://github.com/PrestaShop/ps_shoppingcart/pull/42

### CODE REVIEW

**Comment by Robin-Fischer-PS** [comment]
Hi @matks !

I've noticed 2 bugs for this release (tested on 1.7.7 and 1.7.6) : 

1/ When trying to uninstall, an error message pop (but the uninstall is done) : 
uninstall 1

2/ On FO, the cart is hooked on the wrong display : 
no shopping cart 1

It's in displayTop (screen with release)
new display SC 1

Instead of displayNav2 (screen with release)
old display SC 1

Thanks :smile:

**Comment by matks** [comment]
Hi @Robin-Fischer-PS I'm sorry I'm not sure these are real issues.

1) For the "uninstall" bad notification, I fail to reproduce, I get the happy green notif with `develop` branch for the core (future 1.7.7):
Capture d’écran 2019-10-29 à 15 35 10

2) For the bad hook, you're right it seems to be in a bad place, however this is not related to this release 🤔 the `displayTop` is used in previous version 2.0.2 (see https://github.com/PrestaShop/ps_shoppingcart/blob/v2.0.2/ps_shoppingcart.php#L140). So this bug is not a regression from the previous version.

For 2) I guess we could fix the issue by using `displayNav2` instead of `displayTop` however this means that any theme (or even another module) that relies on ps_shoppingcart module will suddenly see it, when updated, move to another look (although it is a patch version, which is supposed to only fix bugs, not modify behavior) 🤔 ...

**Comment by sarahdib** [comment]
@matks 

I didn't reproduce point 1/

For the point 2 : 
this only happen if you reset the module or like @Robin-Fischer-PS uninstall the module clone the module and install then.

This is not a regression  I try with the previous version.

**Comment by matks** [comment]
OK, I registered issue 2/ in https://github.com/PrestaShop/ps_shoppingcart/issues/52 so we dont lose it. Thanks for QA !

**Pull request merged**
